[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft_anchor = "HyxrJyDobdfRa9FnouLfNKLh5Np3DbaQ5T3ehB9DA9Rq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
